; Control-file for template elements

output   = 
button   = 
checkbox =
column   =
date     = 
dummy    =
focus    = 
form     = 
group    = 
hidden   = name:*,default
header   = name:,views,back:false
editor   = 
else     =
if       = 
image    = 
input    = class:text,default:,type:text,index,name:*,prefix,value,size:,maxlength:256,onchange:,readonly:false,hint:,icon:
inputarea= name,rows:10,cols:40,value,index,onchange,prefix,class:inputarea,default:
insert   = file,script,inline:false,url,name,function
label    = for,value,key,text
link     = title:,config,type:,target,var,url,class:,action,subaction,id,var1,value1,var2,value2,var3,value3,var4,value4,var5,value5,accesskey,name,anchor,frame:_self,modal:false
list     = list:*,extract:false,key:list_key,value:list_value
logo     = name:*
newline  =
page     = class:main,title,menu
part     = id,class
password = name:*,default:,class:,size:40,maxlength:256
radio    = readonly:false,name:*,value,default:false,prefix:,suffix:,class:,onchange:,children,checked
raw      =
row      = class,classes,id
selectbox= list:*,name:*,default,onchange:,title:,class:,addempty:false,multiple:false,size:1,lang:false
radiobox = list:*,name:*,default,onchange:,title:,class:
selector = 
set      = 
table    = 
text     = 
tree     = 
upload   = 
user     = 
window   = 
qrcode   = 