# OpenRat CMS configuration for development in docker
login:
  motd: ""
database-default:
  default-id:  db
database:
  db:
    enabled    :  true
    dsn        :  "${env:DB_TYPE}:host=${env:DB_HOST}; dbname=${env:DB_NAME}"
    description:  "PDO"
    name       :  "PRO"
    user       :  ${env:DB_USER}
    password   :  ${env:DB_PASS}
    base64     :  true                 #  store binary as BASE64 (should be true for postgresql)
    prefix     :  cms_pro1_
    suffix     :  _or
log:
  file :  ""
  level:  "debug"
  stdout: true

production: ${env:CMS_PRODUCTION}

mail:
  client: smtp
  smtp:
    relay:
      host: mail.weiherhei.de
    hostname: "cms.docker.spencer"

publish:
  filesystem:
    directory: /var/www/localhost/public
  
application:
  name: "${env:CMS_NAME?OpenRat CMS}"
  operator: "${env:CMS_OPERATOR?Local}"
  