#!/bin/bash
#
#
VERSION=$1
SCRIPT=`basename "$0"`
CURRENT=`dirname "$0"`
OUTFILE=${CURRENT}/../modules/cms/base/Version.class.php

if   [ -z "$VERSION" ]; then
  echo "Usage: $0 <version>" 1>&2;
  exit 1;
fi


function set_version {
  VERSION=$1

  cat << EOF > $OUTFILE
<?php
// AUTO GENERATED.
// THIS FILE IS GENERATED BY $SCRIPT - DO NOT CHANGE.
namespace cms\base;
class Version {
    const VERSION = '${VERSION}';
}
EOF
}

DATE=`date -R`

set_version $VERSION

#git commit -m "New version tag $VERSION" $OUTFILE
#git tag $VERSION

set_version 'dev-snapshot'

#git commit -m "Setting development status" $OUTFILE
