
# OpenRat CMS configuration
# -------------------------

# This file is YAML formatted.

# Security warning:
# Place your sensitive configuration outside of your document root!
# DO NOT PLACE ANY SENSITIVE INFORMATION HERE - THIS FILE IS WORLD READABLE!

database:
  db:
    enabled : false          # remove this line or set the value to 'true' to enable this database
    dsn     : "mysql:host=localhost; dbname=name_of_db; charset=utf8"
    user    : "dbuser"       # user
    password: "dbpass"       # password (attention: please to NOT place any passwords in the document root)

# It is recommended to place the configuration outside of the document root
#
# Simple example:
# include: /etc/openrat/config.yml
#
# You may use environment variables like
# include: ${env:YOUR_ENV_VAR}.yml
#
# or http header like
# include: /etc/openrat/config-${http:host}.yml
#
include:
  - ./config-${http:host}.yml
